version: 2
before:
  hooks:
    - go mod tidy
builds:
- id: awscleanup_build
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - windows
  goarch:
    - amd64
  binary: aws-cleanup
  ldflags: "-s -w"
archives:
- format: zip
  name_template: "aws-cleanup"
release:
  draft: true